import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      firstName: 'Daniel',
      staffId: 'DV00001',
      lastName: 'Ello',
      email: 'demakventures@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: true,

      image: 'image',
    },
    {
      firstName: 'Matthew',
      staffId: 'DV00025',
      lastName: 'Domi',
      email: 'demakventures1@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
      image: 'image',
    },
    {
      firstName: 'Bless',
      staffId: 'DV00020',
      lastName: 'Anku',
      email: 'demakventures2@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
      image: 'image',
    },
    {
      firstName: 'Benedicta',
      staffId: 'DV00015',
      lastName: 'Gbedema',
      email: 'demakventures3@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
      image: 'image',
    },
    {
      firstName: 'Eric',
      staffId: 'DV00010',
      lastName: 'Anagbonu',
      email: 'demakventures4@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
      image: 'image',
    },
    {
      firstName: 'Daniel',
      staffId: 'DV0005',
      lastName: 'Amada',
      email: 'demakventures5@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
      image: 'image',
    },
    {
      firstName: 'Gloria',
      staffId: 'DV00091',
      lastName: 'Anagbonu',
      email: 'demakventures6@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: true,

      image: 'image',
    },
    {
      firstName: 'Kingsbeth',
      staffId: 'DV0075',
      lastName: 'Midodzi',
      email: 'demakventures7@gmail.com',
      password: bcrypt.hashSync('demak@1234'),
      isAdmin: false,
      image: 'image',
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};
export default data;
